"""Replaceable capability ports for IBM i operations."""

from __future__ import annotations

from pathlib import Path, PurePosixPath
from typing import Any, Protocol, Sequence

from behavior_lab.models import Authority, CommandResult, JobRef, Observation


class LifecycleTransport(Protocol):
    @property
    def authority(self) -> Authority: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def create_workspace(self, library: str, ifs_root: PurePosixPath) -> None: ...
    def cleanup_workspace(self, library: str, ifs_root: PurePosixPath) -> None: ...


class FileTransport(Protocol):
    def upload(self, local: Path, remote: PurePosixPath) -> str: ...
    def inspect_filesystem(self, root: PurePosixPath) -> Observation: ...


class CommandTransport(Protocol):
    def execute_cl(self, command: str) -> CommandResult: ...
    def compile(self, language: str, command: str) -> CommandResult: ...
    def call_program(
        self, library: str, program: str, parameters: Sequence[str]
    ) -> CommandResult: ...


class SqlTransport(Protocol):
    def execute_sql(self, statement: str, parameters: Sequence[Any] = ()) -> Observation: ...
    def capture_database_state(self, specification: dict[str, Any]) -> Observation: ...


class JobTransport(Protocol):
    def submit(self, command: str) -> JobRef: ...
    def wait(self, job: JobRef, timeout_seconds: int) -> str: ...
    def job_log(self, job: JobRef) -> str: ...


class InspectionTransport(Protocol):
    def messages(self, target: str) -> Observation: ...
    def objects(self, library: str) -> Observation: ...
    def locks(self, target: str) -> Observation: ...
    def data_queue(self, library: str, name: str) -> Observation: ...
    def message_queue(self, library: str, name: str) -> Observation: ...
    def spool(self, job: JobRef) -> Observation: ...


class ControlledOperationTransport(Protocol):
    """Optional control plane implemented by future real adapters."""

    def cancel(self, cancellation_token: str, reason: str) -> None: ...
    def recover_execution(self, execution_id: str) -> str: ...
    def detect_stuck_job(self, job: JobRef, threshold_seconds: int) -> bool: ...
    def detect_msgw(self, job: JobRef) -> bool: ...
    def discover_capabilities(self) -> Sequence[dict[str, Any]]: ...
